"""requests table

Revision ID: 43935e6cc695
Revises: e7eda5eaa1b8
Create Date: 2019-03-09 20:32:58.590880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43935e6cc695'
down_revision = 'e7eda5eaa1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('request', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('request', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
